### ISSUE TITLE
Use Custom Font

### ISSUE THREAD

**Issue by vre142** [hamraa/react-native-steps#3]
Hi How can I use Custom Font in your library?

**Comment by hamidrasti** [comment]
@vre142  Hi. you can set fontFamily of label in labelStyle. check the sample project

**Comment by vre142** [comment]
I can't find it in sample project can you tell me with more detail?
Thanks

**Comment by hamidrasti** [comment]
@vre142 You can set like this:

`labelStyle: {
        fontWeight: 'normal',
        fontFamily: 'IranYekanLight',
    },`

in configs object
