### ISSUE TITLE
Labels stopped working

### ISSUE THREAD

**Issue by norre-daroy** [hamraa/react-native-steps#4]
Labels stopped working I upgraded my react-native and got this warning: _'Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`_. Might be the cause why labels stopped working. 

Found the same issue that might help you fix it. 
https://stackoverflow.com/questions/61014661/animated-usenativedriver-was-not-specified-issue-of-reactnativebase-input

Thank you :)

**Comment by hamidrasti** [comment]
Hi, I'm currently so busy to maintain this library. any contribution will appreciate.
